// @ts-nocheck
// eslint-disable
// ---------------------------------------------------
// 🚗🚦 Generated by nuxt-typed-router. Do not modify !
// ---------------------------------------------------

export type RoutePathSchema =
  | '/'
  | '/checkin'
  | '/concorrentes'
  | '/equipe'
  | '/fornecedores'
  | '/login'
  | '/ocorrencias'
  | '/prospectos'
  | '/rotas';

type ValidStringPath<T> = T extends `${string} ${string}` ? false : T extends '' ? false : true;

type ValidParam<T, R extends boolean = true> = T extends `${infer A}/${infer B}`
  ? A extends `${string} ${string}`
    ? false
    : A extends `?${string}`
      ? false
      : A extends `${string} ${string}`
        ? false
        : A extends ''
          ? B extends ''
            ? true
            : false
          : B extends `?${string}`
            ? false
            : B extends `#${string}`
              ? true
              : B extends ''
                ? true
                : false
  : R extends true
    ? T extends ''
      ? false
      : ValidParam<T, false>
    : T extends `?${string}`
      ? false
      : T extends `${string} ${string}`
        ? false
        : true;

type ValidEndOfPath<T> = T extends `/`
  ? true
  : T extends ''
    ? true
    : T extends `${string} ${string}`
      ? false
      : T extends `?${string}`
        ? true
        : T extends `#${string}`
          ? true
          : false;

type ValidateCheckin<T> = T extends `/checkin${infer TCheckin}`
  ? ValidEndOfPath<TCheckin> extends false
    ? "End of path '/checkin' is invalid"
    : true
  : false;

type ValidateConcorrentes<T> = T extends `/concorrentes${infer TConcorrentes}`
  ? ValidEndOfPath<TConcorrentes> extends false
    ? "End of path '/concorrentes' is invalid"
    : true
  : false;

type ValidateEquipe<T> = T extends `/equipe${infer TEquipe}`
  ? ValidEndOfPath<TEquipe> extends false
    ? "End of path '/equipe' is invalid"
    : true
  : false;

type ValidateFornecedores<T> = T extends `/fornecedores${infer TFornecedores}`
  ? ValidEndOfPath<TFornecedores> extends false
    ? "End of path '/fornecedores' is invalid"
    : true
  : false;

type ValidateLogin<T> = T extends `/login${infer TLogin}`
  ? ValidEndOfPath<TLogin> extends false
    ? "End of path '/login' is invalid"
    : true
  : false;

type ValidateOcorrencias<T> = T extends `/ocorrencias${infer TOcorrencias}`
  ? ValidEndOfPath<TOcorrencias> extends false
    ? "End of path '/ocorrencias' is invalid"
    : true
  : false;

type ValidateProspectos<T> = T extends `/prospectos${infer TProspectos}`
  ? ValidEndOfPath<TProspectos> extends false
    ? "End of path '/prospectos' is invalid"
    : true
  : false;

type ValidateRotas<T> = T extends `/rotas${infer TRotas}`
  ? ValidEndOfPath<TRotas> extends false
    ? "End of path '/rotas' is invalid"
    : true
  : false;

export type ValidatePath<T extends string> = T extends string
  ? T extends '/'
    ? T
    : ValidateCheckin<T> extends true
      ? T
      : ValidateConcorrentes<T> extends true
        ? T
        : ValidateEquipe<T> extends true
          ? T
          : ValidateFornecedores<T> extends true
            ? T
            : ValidateLogin<T> extends true
              ? T
              : ValidateOcorrencias<T> extends true
                ? T
                : ValidateProspectos<T> extends true
                  ? T
                  : ValidateRotas<T> extends true
                    ? T
                    : string extends T
                      ? T
                      : `Error: ${ValidateCheckin<T> | ValidateConcorrentes<T> | ValidateEquipe<T> | ValidateFornecedores<T> | ValidateLogin<T> | ValidateOcorrencias<T> | ValidateProspectos<T> | ValidateRotas<T>}`
  : never;

// RouteNameFromPath, RouteNameFromLocalePath
export type RouteNameFromPath<T extends string> = T extends string
  ? T extends '/'
    ? 'index'
    : ValidateCheckin<T> extends true
      ? 'checkin'
      : ValidateConcorrentes<T> extends true
        ? 'concorrentes'
        : ValidateEquipe<T> extends true
          ? 'equipe'
          : ValidateFornecedores<T> extends true
            ? 'fornecedores'
            : ValidateLogin<T> extends true
              ? 'login'
              : ValidateOcorrencias<T> extends true
                ? 'ocorrencias'
                : ValidateProspectos<T> extends true
                  ? 'prospectos'
                  : ValidateRotas<T> extends true
                    ? 'rotas'
                    : never
  : never;

export type TypedPathParameter<T extends string> = ValidatePath<T> | RoutePathSchema;
